services:
  api:
    build: .
    container_name: fastapi-automatizacion
    env_file:
      - .env
    ports:
      - "${PORT:-8000}:${PORT:-8000}"

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 10.200.0.0/16
